// Mocks generated by Mockito 5.0.12 from annotations
// in flutter_small_test_task/test/clean_arch_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_small_test_task/clean_architecture_like/server/fake_server.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FakeServer].
///
/// See the documentation for Mockito's code generation for more information.
class MockFakeServer extends _i1.Mock implements _i2.FakeServer {
  MockFakeServer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<Map<String, dynamic>>> requestProducts() =>
      (super.noSuchMethod(Invocation.method(#requestProducts, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i3.Future<List<Map<String, dynamic>>>);
  @override
  void addProduct() => super.noSuchMethod(Invocation.method(#addProduct, []),
      returnValueForMissingStub: null);
  @override
  void removeProduct(Map<String, dynamic>? json) =>
      super.noSuchMethod(Invocation.method(#removeProduct, [json]),
          returnValueForMissingStub: null);
}
